#ifndef NAGA_LOGGINGLEVEL_H_
#define NAGA_LOGGINGLEVEL_H_

#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define SPDLOG_FUNCTION __PRETTY_FUNCTION__

// it is insanely hard to dispatch preprocessor on string value
// credit: https://stackoverflow.com/a/45450646/84283
#define NAGA_ACTIVE_LOG_LEVEL_CAT(a, ...) NAGA_ACTIVE_LOG_LEVEL_CAT_IMPL(a, __VA_ARGS__)
#define NAGA_ACTIVE_LOG_LEVEL_CAT_IMPL(a, ...) a##__VA_ARGS__

#define NAGA_ACTIVE_LOG_LEVEL_TRACE 1
#define NAGA_ACTIVE_LOG_LEVEL_DEBUG 2
#define NAGA_ACTIVE_LOG_LEVEL_INFO 3
#define NAGA_ACTIVE_LOG_LEVEL_WARN 4
#define NAGA_ACTIVE_LOG_LEVEL_ERROR 5
#define NAGA_ACTIVE_LOG_LEVEL_CRITICAL 6

#define NAGA_ACTIVE_LOG_LEVEL_VAL NAGA_ACTIVE_LOG_LEVEL_CAT(NAGA_ACTIVE_LOG_LEVEL_, NAGA_ACTIVE_LOG_LEVEL)

#if defined(NAGA_ACTIVE_LOG_LEVEL)
// change SPDLOG_ACTIVE_LEVEL based on NAGA_ACTIVE_LOG_LEVEL passed from build system
#undef SPDLOG_ACTIVE_LEVEL
#if NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_TRACE
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#elif NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_DEBUG
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
#elif NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_INFO
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#elif NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_WARN
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_WARN
#elif NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_ERROR
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_ERROR
#elif NAGA_ACTIVE_LOG_LEVEL_VAL == NAGA_ACTIVE_LOG_LEVEL_CRITICAL
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_CRITICAL
#else
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_OFF
#endif

#endif

#endif