name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NAGA_WORKFLOW_CACHE_DIR: ~/naga-cache

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache docker files
        uses: actions/cache@v1
        with:
          path: ${{ env.NAGA_WORKFLOW_CACHE_DIR }}
          key: naga-cache-2

      - name: Run the CI workflow
        run: ./scripts/workflow-ci.sh
